// This could be autogenerated via Gir, but that would just be too much work
using System;
using System.Runtime.InteropServices;

namespace NickvisionCavalier.GNOME.Helpers;

/// <summary>
/// Helper class for Gtk4LayerShell
/// </summary>
public static class Gtk4LayerShell
{
    /// <summary>
    /// The name of the gtk4 layer shell library
    /// </summary>
    private const string LibName = "libgtk4-layer-shell.so";

    /// <summary>
    /// Initializes the layer shell for a window
    /// </summary>
    /// <param name="window">The window to initialize</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_init_for_window(IntPtr window);

    /// <summary>
    /// Sets the layer of a window
    /// </summary>
    /// <param name="window">The window to set the layer for</param>
    /// <param name="layer">The layer to set</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_set_layer(IntPtr window, GtkLayerShellLayer layer);

    /// <summary>
    /// Sets the anchor of a window corner
    /// </summary>
    /// <param name="window">The window to set the anchor for</param>
    /// <param name="edge">The edge to anchor to</param>
    /// <param name="anchor">Whether to anchor to the edge</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_set_anchor(IntPtr window, GtkLayerShellEdge edge, bool anchor);

    /// <summary>
    /// Sets the exclusive zone of a window
    /// </summary>
    /// <param name="window">The window to set the exclusive zone for</param>
    /// <param name="exclusive_zone">The exclusive zone to set</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_set_exclusive_zone(IntPtr window, int exclusive_zone);

    /// <summary>
    /// Sets the namespace of a window in the layer shell
    /// </summary>
    /// <param name="window">The window to set the namespace for</param>
    /// <param name="name_space">The namespace to set</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_set_namespace(IntPtr window, string name_space);

    /// <summary>
    /// Sets the keyboard mode of a window in the layer shell
    /// </summary>
    /// <param name="window">The window to set the keyboard mode for</param>
    /// <param name="mode">The keyboard mode to set</param>
    [DllImport(LibName)]
    public static extern void gtk_layer_set_keyboard_mode(IntPtr window, GtkLayerShellKeyboardMode mode);
}

/// Keyboard mode for a window in the layer shell
public enum GtkLayerShellKeyboardMode
{
    /// <summary>
    /// No keyboard focus
    /// </summary>
    None = 0,
    /// <summary>
    /// Exclusive keyboard focus
    /// </summary>
    Exclusive = 1,
    /// <summary>
    /// On-demand keyboard focus, i.e. the window will only receive keyboard focus when it is activated
    /// </summary>
    OnDemand = 2
}

/// Layer for a window in the layer shell
public enum GtkLayerShellLayer
{
    /// <summary>
    /// Background layer
    /// </summary>
    Background = 0,
    /// <summary>
    /// Bottom layer. Above background, below windows
    /// </summary>
    Bottom = 1,
    /// <summary>
    /// Top layer. Above windows, below overlay
    /// </summary>
    Top = 2,
    /// <summary>
    /// Overlay layer.
    /// </summary>
    Overlay = 3
}

/// Edges for a window in the layer shell
public enum GtkLayerShellEdge
{
    Left = 0,
    Right = 1,
    Top = 2,
    Bottom = 3
}
